server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: abc15150568124

  servlet:
    multipart:
      enabled: true
      location: E:/projects/hj-movie-manage-service/src/main/resources/static/images
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.hjmovie.demo.mybatis.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true



# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true
